# Gradle JVM 参数
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError

# AndroidX (v2 embedding 必需)
android.useAndroidX=true
android.enableJetifier=true

# 抑制 SDK 34 警告
android.suppressUnsupportedCompileSdk=34

# 启用 R8 完整模式
android.enableR8.fullMode=true

# Gradle 并行
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
